name: Make Apk CI

on:
  push:
    branches: [ all-branches-merged-in-one ]
  pull_request:
    branches: [ all-branches-merged-in-one ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    
  
jobs:
  Build-Apk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v15
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Run nix-shell and Make
      uses: ZenithalHourlyRate/nix-shell-action@v4
      with:
        file: shell.nix
        script: |
          make
    - name: save debug apk
      uses: actions/upload-artifact@v2
      with:
        name: debug apk
        path: _build/*.apk
